# Generated by Django 5.2.5 on 2025-08-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_profile_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
