# Generated by Django 5.2.5 on 2025-08-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/images/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
