# Generated by Django 5.2.5 on 2025-08-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_commentslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentsList',
        ),
    ]
