# Generated by Django 5.2.5 on 2025-08-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_remove_usernewslettersubscription_newsletter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
