# Generated by Django 5.2.5 on 2025-08-09 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_alter_announcementimage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.category'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='AnnouncementImage',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
